# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/41c98965-5fe7-4bf3-8803-67980a898741";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/41c98965-5fe7-4bf3-8803-67980a898741";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/41c98965-5fe7-4bf3-8803-67980a898741";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/E0B4-3440";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/41c98965-5fe7-4bf3-8803-67980a898741";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/41c98965-5fe7-4bf3-8803-67980a898741";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/41c98965-5fe7-4bf3-8803-67980a898741";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/bca2fd8b-cd22-4d39-8a0c-7f94b322e600";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
